version: '3.9'

services:
  postgres:
    image: postgres
    container_name: int20h-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: int20h-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID: ${GOOGLE_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET: ${GOOGLE_SECRET}
    depends_on:
      - postgres

volumes:
  postgres-data:
